name: Test Screen Command2

on:
  workflow_dispatch:  # Allows manual triggering via GitHub UI
    inputs:
      duration:
        description: 'How long to run (in seconds)'
        required: true
        default: '30'

jobs:
  test-screen:
    runs-on: ubuntu-latest  # Change to 'self-hosted' if using your runner

    steps:
      - name: Install screen
        run: sudo apt-get update && sudo apt-get install -y screen

      - name: Start screen session with command
        run: |
          screen -dmL -Logfile /tmp/test.log -S testsession bash -c 'for i in $(seq 1 ${INPUT_DURATION}); do echo "Tick $i"; sleep 1; done'

      - name: Verify screen session is running
        run: |
          screen -ls

      - name: Display initial logs
        run: cat /tmp/test.log

      - name: Wait for session to complete
        run: |
          while screen -list | grep -q "testsession"; do
            echo "Waiting for screen session to finish..."; sleep 5;
          done

      - name: Display final logs
        run: cat /tmp/test.log

      - name: Upload screen log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: screen-log
          path: /tmp/test.log
