name: Test Nohup Command

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'How long to run (in seconds)'
        required: true
        default: '30'

jobs:
  test-nohup:
    runs-on: ubuntu-latest  # Change to 'self-hosted' if using your own runner

    steps:
      - name: Start nohup session with command
        run: |
          nohup bash -c 'for i in $(seq 1 ${INPUT_DURATION}); do echo "Tick $i"; sleep 1; done' > /tmp/test.log 2>&1 &
          echo $! > /tmp/test.pid

      - name: Wait for session to complete
        run: |
          while kill -0 $(cat /tmp/test.pid) 2> /dev/null; do
            echo "Waiting for nohup session to finish..."
            sleep 5
          done
          cat /tmp/test.log

      - name: Upload nohup log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: nohup-log
          path: /tmp/test.log
