name: Test option menu

on:
  workflow_dispatch:
    inputs:
      defconfig:
        description: "Select defconfig"
        required: false
        default: "ci-default"
        type: choice
        options:
          - "ci-default"
          - "xfs_reflink_4k"
          - "xfs_nocrc_4k"
      soak:
        description: "Select soak duration"
        required: false
        default: "No soak"
        type: choice
        options:
          - "No soak"
          - "Low - 30 minutes"
          - "Mid - 1 hour"
          - "High - 2.5 hours"
          - "Pathological - 48 hours"
      tests:
        description: "Select additional test coverage"
        required: false
        default: "ci-default-test"
        type: choice
        options:
          - "ci-default-test"
          - "generic/003"
          - "generic/751"

jobs:
  test-options:
    name: Test options menu
    runs-on: ubuntu-latest
      - name: Run nohup with unbuffered output
        run: |
          nohup stdbuf -oL bash -c 'for i in $(seq 1 30); do echo "$i: soak: ${{ github.event.inputs.defconfig }} ${{ github.event.inputs.soak }} ${{ github.event.inputs.tests }}"; sleep 1; done' > /tmp/test.log 2>&1 &
          echo $! > /tmp/test.pid
          while kill -0 $(cat /tmp/test.pid) 2> /dev/null; do
            echo "Waiting for nohup session to finish..."
            sleep 5
          done

      - name: Display final logs
        run: |
          if [ "${{ github.event.inputs.defconfig }}" == "ci-default" ]; then
            echo "${{ github.event.inputs.defconfig }} was used" > /tmp/ci-default.txt
          elif [ "${{ github.event.inputs.defconfig }}" == "xfs_reflink_4k" ]; then
            echo "${{ github.event.inputs.defconfig }} was used" > /tmp/xfs_reflink_4k.txt
          elif [ "${{ github.event.inputs.defconfig }}" == "xfs_nocrc_4k" ]; then
            echo "${{ github.event.inputs.defconfig }} was used" > /tmp/xfs_nocrc_4k.txt
          else
            echo "No option was used for defconfig" > /tmp/empty.txt
          fi

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-log
          path: |
            /tmp/test.log
            /tmp/ci-default.txt
            /tmp/xfs_reflink_4k.txt
            /tmp/xfs_nocrc_4k.txt
            /tmp/empty.txt
