name: Test option menu

on:
  workflow_dispatch:
    inputs:
      defconfig:
        description: "Select defconfig"
        required: false
        default: "ci-default"
        type: choice
        options:
          - "ci-default"
          - "xfs_reflink_4k"
          - "xfs_nocrc_4k"
      soak:
        description: "Select soak duration"
        required: false
        default: "No soak"
        type: choice
        options:
          - "No soak"
          - "Low - 30 minutes"
          - "Mid - 1 hour"
          - "High - 2.5 hours"
          - "Pathological - 48 hours"
      tests:
        description: "Select additional test coverage"
        required: false
        default: "ci-default-test"
        type: choice
        options:
          - "ci-default-test"
          - "generic/003"
          - "generic/751"

jobs:
  test-screen:
    runs-on: ubuntu-latest

      - name: Run nohup with unbuffered output
        run: |
          nohup stdbuf -oL bash -c 'for i in $(seq 1 30); do echo "$i: soak: ${{ github.event.inputs.defconfig }} ${{ github.event.inputs.soak }} ${{ github.event.inputs.tests }}"; sleep 1; done' > /tmp/test.log 2>&1 &
          echo $! > /tmp/test.pid
          while kill -0 $(cat /tmp/test.pid) 2> /dev/null; do
            echo "Waiting for nohup session to finish..."
            sleep 5
          done

      - name: Display final logs
        run: |
          if [ "${{ inputs.task_name }}" == "Task A" ]; then
            cat /tmp/task_a.log
          elif [ "${{ inputs.task_name }}" == "Task B" ]; then
            cat /tmp/task_b.log
          else
            cat /tmp/task_c.log
          fi

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-log
          path: |
            /tmp/task_a.log
            /tmp/task_b.log
            /tmp/task_c.log
