name: Test Screen Command

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'How long to run (in seconds)'
        required: true
        default: '30'

jobs:
  test-screen:
    runs-on: ubuntu-latest  # Change to 'self-hosted' if using your own runner

    steps:
      - name: Install screen
        run: sudo apt-get update && sudo apt-get install -y screen

      - name: Start and monitor screen session
        run: |
          screen -dmL -Logfile /tmp/test.log -S testsession bash -c 'for i in $(seq 1 ${INPUT_DURATION}); do echo "Tick $i"; sleep 1; done'
          while screen -list | grep -q "testsession"; do
            echo "Waiting for screen session to finish..."
            sleep 5
          done
          cat /tmp/test.log

      - name: Upload screen log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: screen-log
          path: /tmp/test.log
